[
  {
    resource: "/d:/Projects/own/bulwark/vite.config.js",
    owner: "eslint3",
    code: {
      value: "no-undef",
      target: {
        $mid: 1,
        path: "/docs/latest/rules/no-undef",
        scheme: "https",
        authority: "eslint.org",
      },
    },
    severity: 8,
    message: "'__dirname' is not defined.",
    source: "eslint",
    startLineNumber: 14,
    startColumn: 23,
    endLineNumber: 14,
    endColumn: 32,
    modelVersionId: 1,
    origin: "extHost1",
  },
  {
    resource: "/d:/Projects/own/bulwark/vite.config.js",
    owner: "eslint3",
    code: {
      value: "no-undef",
      target: {
        $mid: 1,
        path: "/docs/latest/rules/no-undef",
        scheme: "https",
        authority: "eslint.org",
      },
    },
    severity: 8,
    message: "'__dirname' is not defined.",
    source: "eslint",
    startLineNumber: 15,
    startColumn: 26,
    endLineNumber: 15,
    endColumn: 35,
    modelVersionId: 1,
    origin: "extHost1",
  },
  {
    resource: "/d:/Projects/own/bulwark/vite.config.js",
    owner: "eslint3",
    code: {
      value: "no-undef",
      target: {
        $mid: 1,
        path: "/docs/latest/rules/no-undef",
        scheme: "https",
        authority: "eslint.org",
      },
    },
    severity: 8,
    message: "'__dirname' is not defined.",
    source: "eslint",
    startLineNumber: 16,
    startColumn: 24,
    endLineNumber: 16,
    endColumn: 33,
    modelVersionId: 1,
    origin: "extHost1",
  },
  {
    resource: "/d:/Projects/own/bulwark/vite.config.js",
    owner: "eslint3",
    code: {
      value: "no-undef",
      target: {
        $mid: 1,
        path: "/docs/latest/rules/no-undef",
        scheme: "https",
        authority: "eslint.org",
      },
    },
    severity: 8,
    message: "'__dirname' is not defined.",
    source: "eslint",
    startLineNumber: 17,
    startColumn: 27,
    endLineNumber: 17,
    endColumn: 36,
    modelVersionId: 1,
    origin: "extHost1",
  },
  {
    resource: "/d:/Projects/own/bulwark/vite.config.js",
    owner: "eslint3",
    code: {
      value: "no-undef",
      target: {
        $mid: 1,
        path: "/docs/latest/rules/no-undef",
        scheme: "https",
        authority: "eslint.org",
      },
    },
    severity: 8,
    message: "'__dirname' is not defined.",
    source: "eslint",
    startLineNumber: 18,
    startColumn: 26,
    endLineNumber: 18,
    endColumn: 35,
    modelVersionId: 1,
    origin: "extHost1",
  },
  {
    resource: "/d:/Projects/own/bulwark/vite.config.js",
    owner: "eslint3",
    code: {
      value: "no-undef",
      target: {
        $mid: 1,
        path: "/docs/latest/rules/no-undef",
        scheme: "https",
        authority: "eslint.org",
      },
    },
    severity: 8,
    message: "'__dirname' is not defined.",
    source: "eslint",
    startLineNumber: 19,
    startColumn: 28,
    endLineNumber: 19,
    endColumn: 37,
    modelVersionId: 1,
    origin: "extHost1",
  },
  {
    resource: "/d:/Projects/own/bulwark/vite.config.js",
    owner: "eslint3",
    code: {
      value: "no-undef",
      target: {
        $mid: 1,
        path: "/docs/latest/rules/no-undef",
        scheme: "https",
        authority: "eslint.org",
      },
    },
    severity: 8,
    message: "'__dirname' is not defined.",
    source: "eslint",
    startLineNumber: 20,
    startColumn: 27,
    endLineNumber: 20,
    endColumn: 36,
    modelVersionId: 1,
    origin: "extHost1",
  },
  {
    resource: "/d:/Projects/own/bulwark/vite.config.js",
    owner: "eslint3",
    code: {
      value: "no-undef",
      target: {
        $mid: 1,
        path: "/docs/latest/rules/no-undef",
        scheme: "https",
        authority: "eslint.org",
      },
    },
    severity: 8,
    message: "'__dirname' is not defined.",
    source: "eslint",
    startLineNumber: 21,
    startColumn: 26,
    endLineNumber: 21,
    endColumn: 35,
    modelVersionId: 1,
    origin: "extHost1",
  },
  {
    resource: "/d:/Projects/own/bulwark/vite.config.js",
    owner: "eslint3",
    code: {
      value: "no-undef",
      target: {
        $mid: 1,
        path: "/docs/latest/rules/no-undef",
        scheme: "https",
        authority: "eslint.org",
      },
    },
    severity: 8,
    message: "'__dirname' is not defined.",
    source: "eslint",
    startLineNumber: 22,
    startColumn: 27,
    endLineNumber: 22,
    endColumn: 36,
    modelVersionId: 1,
    origin: "extHost1",
  },
  {
    resource: "/d:/Projects/own/bulwark/vite.config.js",
    owner: "eslint3",
    code: {
      value: "no-undef",
      target: {
        $mid: 1,
        path: "/docs/latest/rules/no-undef",
        scheme: "https",
        authority: "eslint.org",
      },
    },
    severity: 8,
    message: "'__dirname' is not defined.",
    source: "eslint",
    startLineNumber: 23,
    startColumn: 25,
    endLineNumber: 23,
    endColumn: 34,
    modelVersionId: 1,
    origin: "extHost1",
  },
  {
    resource: "/d:/Projects/own/bulwark/vite.config.js",
    owner: "eslint3",
    code: {
      value: "no-undef",
      target: {
        $mid: 1,
        path: "/docs/latest/rules/no-undef",
        scheme: "https",
        authority: "eslint.org",
      },
    },
    severity: 8,
    message: "'__dirname' is not defined.",
    source: "eslint",
    startLineNumber: 24,
    startColumn: 28,
    endLineNumber: 24,
    endColumn: 37,
    modelVersionId: 1,
    origin: "extHost1",
  },
  {
    resource: "/d:/Projects/own/bulwark/vite.config.js",
    owner: "eslint3",
    code: {
      value: "no-undef",
      target: {
        $mid: 1,
        path: "/docs/latest/rules/no-undef",
        scheme: "https",
        authority: "eslint.org",
      },
    },
    severity: 8,
    message: "'__dirname' is not defined.",
    source: "eslint",
    startLineNumber: 25,
    startColumn: 26,
    endLineNumber: 25,
    endColumn: 35,
    modelVersionId: 1,
    origin: "extHost1",
  },
];
