const { fontawesomeSubset } = require("fontawesome-subset");

fontawesomeSubset(
  {
    solid: [
      "arrow-left",
      "arrow-right",
      "bars",
      "xmark",
      "brain",
      "briefcase",
      "building-columns",
      "check",
      "chevron-down",
      "chevron-left",
      "chevron-right",
      "circle-info",
      "circle-notch",
      "comment-medical",
      "envelope",
      "hand-holding-dollar",
      "hand-holding-heart",
      "handshake",
      "handshake-angle",
      "house",
      "lock",
      "phone",
      "print",
      "scale-balanced",
      "seedling",
      "shield-halved",
      "user-check",
      "users-gear",
    ],
    regular: ["copy"],
    brands: ["facebook", "instagram", "linkedin", "telegram", "youtube"],
  },
  "src/assets/fonts/fa-subset",
);
